# Generated by Django 6.0.4 on 2026-05-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=100)),
                ('user_message', models.TextField()),
                ('bot_response', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=100)),
                ('Flags', models.CharField(max_length=10)),
                ('Utterance', models.TextField()),
                ('Category', models.CharField(max_length=10)),
                ('Intent', models.CharField(max_length=10)),
            ],
        ),
    ]
