# Generated by Django 6.0.4 on 2026-05-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='Category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='Flags',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='Intent',
            field=models.CharField(max_length=100),
        ),
    ]
